# Generated by Django 2.2.5 on 2019-09-24 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name="participant's name")),
                ('email', models.EmailField(max_length=254, verbose_name="participant's email")),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter your 10 digit phone number without country codes and symbols', regex='^\\d{10}$')], verbose_name="participant's phone")),
                ('college', models.CharField(blank=True, max_length=1024, verbose_name="participant's institution")),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(choices=[('EMB', 'Embibe'), ('MIC', 'Micron'), ('QUA', 'Qualcomm'), ('PWC', 'PWC')], max_length=3)),
                ('presentation', models.FileField(null=True, upload_to='', validators=[portal.validators.FileValidator(content_types=('application/pdf', 'application/vnd.ms-powerpoint', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.openxmlformats-officedocument.presentationml.slideshow'), max_size=104857600)])),
                ('submission', models.URLField(blank=True)),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant1', to='portal.Participant')),
                ('participant2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant2', to='portal.Participant')),
                ('participant3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant3', to='portal.Participant')),
                ('participant4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant4', to='portal.Participant')),
            ],
        ),
    ]
