# Generated by Django 2.2.5 on 2019-09-27 21:27

from django.db import migrations, models
import django.db.models.deletion
import portal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='participant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant2', to='portal.Participant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='participant3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant3', to='portal.Participant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='participant4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant4', to='portal.Participant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[portal.validators.FileValidator(content_types=('application/pdf', 'application/vnd.ms-powerpoint', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.openxmlformats-officedocument.presentationml.slideshow'), max_size=104857600)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='problem',
            field=models.CharField(blank=True, choices=[('EMB', 'Embibe'), ('MIC', 'Micron'), ('QUA', 'Qualcomm'), ('PWC', 'PWC')], max_length=3),
        ),
    ]
